repos:
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.0.3
    hooks:
      - id: detect-secrets
        args:
          [
            "--baseline",
            ".secrets.baseline",
            "--word-list",
            "secrets-allow-list.txt",
          ]
        additional_dependencies:
          - pyahocorasick
